project_id = "obnmevwjgleelpvmstjd"

[functions.msg91-verify-otp]
verify_jwt = false

[functions.ensure-phone-user]
verify_jwt = false

[functions.msg91-otp]
verify_jwt = false

[functions.razorpay-create-order]
verify_jwt = false

[functions.razorpay-verify-payment]
verify_jwt = false

[functions.razorpay-recover-payment]
verify_jwt = false

[functions.razorpay-webhook]
verify_jwt = false


[functions.staff-otp]
verify_jwt = false

[functions.razorpay-service-payment]
verify_jwt = false
