import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: { "2xl": "1400px" },
    },
    extend: {
      fontFamily: {
        sans: ['Manrope', '-apple-system', 'BlinkMacSystemFont', 'Helvetica Neue', 'Helvetica', 'Arial', 'system-ui', 'sans-serif'],
        display: ['Sora', '-apple-system', 'BlinkMacSystemFont', 'Helvetica Neue', 'Helvetica', 'Arial', 'system-ui', 'sans-serif'],
        mono: ['ui-monospace', 'SF Mono', 'SFMono-Regular', 'Menlo', 'Consolas', 'monospace'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        critical: { DEFAULT: "hsl(var(--critical))", soft: "hsl(var(--critical-soft))" },
        warning: { DEFAULT: "hsl(var(--warning))", soft: "hsl(var(--warning-soft))" },
        success: { DEFAULT: "hsl(var(--success))", soft: "hsl(var(--success-soft))" },
        info: { DEFAULT: "hsl(var(--info))", soft: "hsl(var(--info-soft))" },
        "neon-green": "hsl(var(--neon-green))",
        "neon-blue": "hsl(var(--neon-blue))",
        "soft-red": "hsl(var(--soft-red))",
        "coral": "hsl(var(--coral))",
        "brand-amber": "hsl(var(--amber))",
        "lime": "hsl(var(--lime))",
        "surface": "hsl(var(--surface))",
        "surface-2": "hsl(var(--surface-2))",
        "surface-3": "hsl(var(--surface-3))",
        // BBDO brand tokens — direct utility access
        bbdo: {
          bg: "var(--bbdo-bg)",
          cream: "var(--bbdo-cream)",
          cream2: "var(--bbdo-cream-2)",
          paper: "var(--bbdo-paper)",
          surface: "var(--bbdo-cream-2)",
          surface2: "var(--bbdo-cream-2)",
          ink: "var(--bbdo-ink)",
          inksoft: "var(--bbdo-ink-soft)",
          line: "var(--bbdo-line)",
          blue: "var(--bbdo-blue)",
          bluedeep: "var(--bbdo-blue-deep)",
          bluesoft: "var(--bbdo-blue-soft)",
          red: "var(--bbdo-red)",
          redsoft: "var(--bbdo-red-soft)",
          mint: "var(--bbdo-mint)",
          mintsoft: "var(--bbdo-mint-soft)",
          lime: "var(--bbdo-lime)",
          amber: "var(--bbdo-amber)",
          maroon: "var(--bbdo-blue-deep)",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xl: "1rem",
        "2xl": "1.25rem",
        "3xl": "1.5rem",
      },
      boxShadow: {
        card: "0 1px 2px rgba(15,26,61,0.04), 0 8px 24px -12px rgba(15,26,61,0.10)",
        lift: "0 2px 4px rgba(15,26,61,0.06), 0 20px 40px -20px rgba(15,26,61,0.16)",
      },
      transitionTimingFunction: {
        bbdo: "cubic-bezier(0.22, 1, 0.36, 1)",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "rise": { from: { opacity: "0", transform: "translateY(8px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "fade-in": { from: { opacity: "0" }, to: { opacity: "1" } },
        "fade-out": { from: { opacity: "1" }, to: { opacity: "0" } },
        "spin-slow": { from: { transform: "rotate(0deg)" }, to: { transform: "rotate(360deg)" } },
        "shimmer": { "0%": { backgroundPosition: "-200% 0" }, "100%": { backgroundPosition: "200% 0" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s cubic-bezier(0.22,1,0.36,1)",
        "accordion-up": "accordion-up 0.2s cubic-bezier(0.22,1,0.36,1)",
        "rise": "rise 0.22s cubic-bezier(0.22,1,0.36,1) both",
        "slide-up": "rise 0.22s cubic-bezier(0.22,1,0.36,1) both",
        "fade-in": "fade-in 0.2s cubic-bezier(0.22,1,0.36,1) both",
        "fade-out": "fade-out 0.16s cubic-bezier(0.22,1,0.36,1) both",
        "scale-in": "fade-in 0.2s cubic-bezier(0.22,1,0.36,1) both",
        "pulse-glow": "fade-in 0.2s cubic-bezier(0.22,1,0.36,1) both",
        "float": "fade-in 0.2s cubic-bezier(0.22,1,0.36,1) both",
        "spin-slow": "spin-slow 8s linear infinite",
        "shimmer": "shimmer 2s linear infinite",
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "bbdo-gradient": "var(--bbdo-gradient)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} as Config;
