// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.5";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-my-profile.ts
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Fetch the signed-in member's health profile: name, age, gender, goals, body stats and coach.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select(
      "name, age, gender, goals, height, weight, bmi, bmi_category, waist, coach_name, onboarding_completed, city, country, initial_health_score"
    ).eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No profile found for this account." }] };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/list-health-logs.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";
var list_health_logs_default = defineTool2({
  name: "list_health_logs",
  title: "List health logs",
  description: "List the signed-in member's recent health logs (weight, steps, glucose, blood pressure), newest first.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(20).describe("How many entries to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("health_logs").select("logged_at, log_type, weight_kg, steps_count, glucose_morning, glucose_evening, bp_systolic, bp_diastolic").eq("user_id", ctx.getUserId()).order("logged_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { logs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/log-health-entry.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var log_health_entry_default = defineTool3({
  name: "log_health_entry",
  title: "Log a health entry",
  description: "Record a health log for the signed-in member. Provide at least one measurement (weight, steps, glucose or blood pressure).",
  inputSchema: {
    log_type: z2.string().trim().min(1).default("manual").describe("Entry type, e.g. weight, glucose, activity."),
    logged_at: z2.string().trim().min(1).nullable().default(null).describe("ISO timestamp; defaults to now."),
    weight_kg: z2.number().positive().max(500).nullable().default(null),
    steps_count: z2.number().int().min(0).max(2e5).nullable().default(null),
    glucose_morning: z2.number().min(0).max(1e3).nullable().default(null),
    glucose_evening: z2.number().min(0).max(1e3).nullable().default(null),
    bp_systolic: z2.number().int().min(0).max(300).nullable().default(null),
    bp_diastolic: z2.number().int().min(0).max(300).nullable().default(null)
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const measurements = {
      weight_kg: input.weight_kg,
      steps_count: input.steps_count,
      glucose_morning: input.glucose_morning,
      glucose_evening: input.glucose_evening,
      bp_systolic: input.bp_systolic,
      bp_diastolic: input.bp_diastolic
    };
    if (Object.values(measurements).every((value) => value === null || value === void 0)) {
      return {
        content: [{ type: "text", text: "Provide at least one measurement to log." }],
        isError: true
      };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("health_logs").insert({
      user_id: ctx.getUserId(),
      log_type: input.log_type ?? "manual",
      logged_at: input.logged_at ?? (/* @__PURE__ */ new Date()).toISOString(),
      ...measurements
    }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Logged: ${JSON.stringify(data)}` }],
      structuredContent: { log: data }
    };
  }
});

// src/lib/mcp/tools/get-my-subscription.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_my_subscription_default = defineTool4({
  name: "get_my_subscription",
  title: "Get my subscription",
  description: "Fetch the signed-in member's current plan, status, start date and expiry.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("subscriptions").select("plan_name, plan_price, duration_months, started_at, expires_at, status, change_type").eq("user_id", ctx.getUserId()).order("started_at", { ascending: false }).limit(5);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { subscriptions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-supplement-plans.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_my_supplement_plans_default = defineTool5({
  name: "list_my_supplement_plans",
  title: "List my supplement plans",
  description: "List supplement plans assigned to the signed-in member by their coach.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("user_supplement_plans").select("plan_name, start_date, duration_weeks, status, notes").eq("user_id", ctx.getUserId()).order("start_date", { ascending: false }).limit(20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { plans: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ogmhspwsvzvwqoavlxjn";
var mcp_default = defineMcp({
  name: "health-journey",
  title: "Health Journey",
  version: "0.1.0",
  instructions: "Tools for the Health Journey app. Every tool acts as the signed-in member: read their health profile, recent health logs, subscription and coach-assigned supplement plans, and log new health entries.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_profile_default, list_health_logs_default, log_health_entry_default, get_my_subscription_default, list_my_supplement_plans_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
